#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x6112910956F6F8B8 (martin@cloudflare.com)
#
Name     : pypi-cloudflare
Version  : 2.8.15
Release  : 29
URL      : https://files.pythonhosted.org/packages/f9/b1/42b74b3f19609a63c42fb0c8a5474a98aa72f1d122cf3eea57ff27e8ac01/cloudflare-2.8.15.tar.gz
Source0  : https://files.pythonhosted.org/packages/f9/b1/42b74b3f19609a63c42fb0c8a5474a98aa72f1d122cf3eea57ff27e8ac01/cloudflare-2.8.15.tar.gz
Source1  : https://files.pythonhosted.org/packages/f9/b1/42b74b3f19609a63c42fb0c8a5474a98aa72f1d122cf3eea57ff27e8ac01/cloudflare-2.8.15.tar.gz.asc
Summary  : Python wrapper for the Cloudflare v4 API
Group    : Development/Tools
License  : MIT
Requires: pypi-cloudflare-bin = %{version}-%{release}
Requires: pypi-cloudflare-license = %{version}-%{release}
Requires: pypi-cloudflare-man = %{version}-%{release}
Requires: pypi-cloudflare-python = %{version}-%{release}
Requires: pypi-cloudflare-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(beautifulsoup4)
BuildRequires : pypi(jsonlines)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(requests)

%description
=================
        
        Installation
        ------------
        
        Two methods are provided to install this software. Use PyPi (see

%package bin
Summary: bin components for the pypi-cloudflare package.
Group: Binaries
Requires: pypi-cloudflare-license = %{version}-%{release}

%description bin
bin components for the pypi-cloudflare package.


%package license
Summary: license components for the pypi-cloudflare package.
Group: Default

%description license
license components for the pypi-cloudflare package.


%package man
Summary: man components for the pypi-cloudflare package.
Group: Default

%description man
man components for the pypi-cloudflare package.


%package python
Summary: python components for the pypi-cloudflare package.
Group: Default
Requires: pypi-cloudflare-python3 = %{version}-%{release}

%description python
python components for the pypi-cloudflare package.


%package python3
Summary: python3 components for the pypi-cloudflare package.
Group: Default
Requires: python3-core
Provides: pypi(cloudflare)
Requires: pypi(beautifulsoup4)
Requires: pypi(jsonlines)
Requires: pypi(pyyaml)
Requires: pypi(requests)

%description python3
python3 components for the pypi-cloudflare package.


%prep
%setup -q -n cloudflare-2.8.15
cd %{_builddir}/cloudflare-2.8.15
pushd ..
cp -a cloudflare-2.8.15 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1653009607
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cloudflare
cp %{_builddir}/cloudflare-2.8.15/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cloudflare/1857fba4ea5c0240235ad8374c2a15727733798e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
## install_append content
sitedir=$(python -c "import sys; print(sys.path[-1])")
rm -rf %{buildroot}/${sitedir}/examples
man1dir=%{buildroot}/usr/share/man/man1
mkdir -pv $man1dir
mv -v %{buildroot}/usr/man/man1/cli4.man $man1dir/cli4.1
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot}/usr/share/clear/optimized-elf/ %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cli4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cloudflare/1857fba4ea5c0240235ad8374c2a15727733798e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cli4.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
